### ISSUE TITLE
Need bower.json to install dependencies.

### ISSUE THREAD

**Issue by gmkou** [sassy/l10n-sample#1]
Need bower.json to install dependencies.

```
$ bower install
bower                           ENOENT No bower.json present
```

**Comment by sassy** [comment]
@gmkou 

Sorry... I mistook .gitignore file.
On Instead, following command.

```
bower install l10n
```

I will fix it later.

**Comment by sassy** [comment]
https://github.com/sassy/l10n-sample/commit/2eb8811718a92b65905c1bad94e28ca0956da7b0
